graph TD
    subgraph Cliente ["👤 CLIENTE"]
        direction TB
        Start((Inicio)) -->|1. Tienda| SolicitaPedido[Solicita Pedido]
        RecibeProd[7. Recibe Mercadería]
        PagaEfectivo[10. Paga en Efectivo] --> End((Fin))
    end

    subgraph Vendedor ["🧑‍💼 VENDEDOR"]
        direction TB
        SolicitaPedido -->|2. Toma pedido| CargaApp[3. Carga pedido en App]
        CargaApp -.->|4. Confirmación| EntregaFisica[6. Entrega Física]
        EntregaFisica --> RecibeProd
        RecibeProd -->|8. Inicia cobro| ProcesaPOS[9. Procesa en POS]
        ProcesaPOS --> PagaEfectivo
    end

    subgraph Sistemas ["💻 SISTEMAS"]
        direction TB
        CargaApp ==> AppBD(App & Base de Datos)
        AppBD ==> InvBD{GESTIÓN STOCK: Reservado}
        InvBD -.-> CargaApp

        ProcesaPOS ==> EmiteTick[Generar Ticket]
        EmiteTick ==> InvBDFinal{STOCK: Baja Definitiva}
        
        PagaEfectivo -.-> Arqueo((Arqueo Caja))
    end

    %% Enlaces de lógica
    AppBD --- InvBD
    EmiteTick --- InvBDFinal